=== HughP/mdettla/trunk/xml/lab04/transakcje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.owocex.pl"
  xmlns="http://www.owocex.pl"
  elementFormDefault="qualified">

  <!-- główny opis zawartości dokumentu -->

  <xs:element name="transakcje">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="zamowienia">
	  <xs:complexType>
	    <xs:choice maxOccurs="unbounded">
	      <xs:element name="zamowienie-maly-sklep" type="zamowienie-maly-sklep"/>
	      <xs:element name="zamowienie-hipermarket" type="zamowienie-hipermarket"/>
	      <xs:element name="zamowienie-hurtownia" type="zamowienie-hurtownia"/>
	    </xs:choice>
	  </xs:complexType>
	</xs:element>
	<xs:element name="dostawy">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="dostawa" type="dostawa" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- deklaracje typów -->

  <xs:complexType name="zamowienie-maly-sklep">
    <xs:complexContent>
      <xs:extension base="zamowienie">
	<xs:sequence>
	  <xs:element name="wielkosc-zamowienia" type="xs:integer"/>
	</xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="zamowienie-hipermarket">
    <xs:complexContent>
      <xs:extension base="zamowienie">
	<xs:sequence>
	  <xs:element name="wielkosc-zamowienia">
	    <xs:simpleType>
	      <xs:restriction base="xs:integer">
		<xs:minInclusive value="500"/>
	      </xs:restriction>
	    </xs:simpleType>
	  </xs:element>
	  <xs:element name="proponowana-cena" type="cena" minOccurs="0"/>
	  <xs:element name="oplata-za-ekspozycje" type="cena"/>
	</xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="zamowienie-hurtownia">
    <xs:complexContent>
      <xs:extension base="zamowienie">
	<xs:sequence>
	  <xs:element name="wielkosc-zamowienia">
	    <xs:simpleType>
	      <xs:restriction base="xs:integer">
		<xs:minInclusive value="500"/>
	      </xs:restriction>
	    </xs:simpleType>
	  </xs:element>
	  <xs:element name="proponowana-cena" type="cena" minOccurs="0"/>
	</xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- typ stanowiący podstawę dla bardziej szczegółowych zamówień -->
  <xs:complexType name="zamowienie">
    <xs:sequence>
      <xs:element name="owoc" type="owoc"/>
      <xs:element name="odbiorca" type="podmiot-gospodarczy"/>
      <xs:element name="data" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="dostawa">
    <xs:sequence>
      <xs:element name="owoc" type="owoc"/>
      <xs:element name="wielkosc-dostawy" type="xs:positiveInteger"/>
      <xs:element name="dostawca" type="podmiot-gospodarczy"/>
      <xs:element name="firma-transportowa" type="podmiot-gospodarczy"/>
      <xs:element name="data" type="xs:date"/>
      <xs:element name="data-przydatnosci" type="xs:date"/>
      <xs:element name="jakosc">
	<xs:simpleType>
	  <xs:restriction base="xs:integer">
	    <xs:minInclusive value="1"/>
	    <xs:maxInclusive value="2"/>
	  </xs:restriction>
	</xs:simpleType>
      </xs:element>
      <xs:element name="cena" type="cena"/>
      <xs:element name="opis-uszkodzen" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="podmiot-gospodarczy">
    <xs:sequence>
      <xs:element name="nazwa" type="xs:string"/>
      <xs:element name="adres" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="owoc">
    <xs:sequence>
      <xs:element name="gatunek" type="xs:string"/>
      <xs:element name="odmiana" type="xs:string"/>
      <xs:element name="kaliber">
	<xs:simpleType>
	  <xs:restriction base="xs:integer">
	    <xs:minInclusive value="1"/>
	    <xs:maxInclusive value="5"/>
	  </xs:restriction>
	</xs:simpleType>
      </xs:element>
      <xs:element name="dodatkowe-informacje" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rodzaj" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="cena">
    <xs:simpleContent>
      <xs:extension base="xs:positiveInteger">
	<xs:attribute name="waluta" default="EUR">
	  <xs:simpleType>
	    <xs:restriction base="xs:string">
	      <xs:enumeration value="USD"/>
	      <xs:enumeration value="EUR"/>
	      <xs:enumeration value="PLN"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== HughP/mdettla/xml/lab04/transakcje.xml
<?xml version="1.0" encoding="UTF-8"?>
<transakcje
  xmlns="http://www.owocex.pl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.owocex.pl transakcje.xsd">
  <zamowienia>
    <zamowienie-hipermarket>
      <owoc rodzaj="marchewka">
	<gatunek>marchevcus pospolitus</gatunek>
	<odmiana>Malezyjska</odmiana>
	<kaliber>4</kaliber>
      </owoc>
      <odbiorca>
	<nazwa>Real</nazwa>
	<adres>Nierealna 16, 23-442 Kielce</adres>
      </odbiorca>
      <data>2009-04-12</data>
      <wielkosc-zamowienia>600</wielkosc-zamowienia>
      <proponowana-cena waluta="PLN">5</proponowana-cena>
      <oplata-za-ekspozycje>1000</oplata-za-ekspozycje>
    </zamowienie-hipermarket>
    <zamowienie-maly-sklep>
      <owoc rodzaj="truskawka">
	<gatunek>truscavicus pospolitus</gatunek>
	<odmiana>Szwedzka</odmiana>
	<kaliber>3</kaliber>
	<dodatkowe-informacje>Dobra na trawienie, ulży bolączkom</dodatkowe-informacje>
      </owoc>
      <odbiorca>
	<nazwa>U Genowefy</nazwa>
	<adres>Alabastrowa 15, 22-666 Wałbrzych</adres>
      </odbiorca>
      <data>2009-03-01</data>
      <wielkosc-zamowienia>50</wielkosc-zamowienia>
    </zamowienie-maly-sklep>
  </zamowienia>
  <dostawy>
    <dostawa>
      <owoc rodzaj="truskawka">
	<gatunek>truscavicus pospolitus</gatunek>
	<odmiana>Szwedzka</odmiana>
	<kaliber>3</kaliber>
	<dodatkowe-informacje>Dobra na trawienie</dodatkowe-informacje>
      </owoc>
      <wielkosc-dostawy>20</wielkosc-dostawy>
      <dostawca>
	<nazwa>Truskawki-to-my</nazwa>
	<adres>Truskawkowa 15, 22-666 Wałbrzych</adres>
      </dostawca>
      <firma-transportowa>
	<nazwa>Fedex-ovotz</nazwa>
	<adres>Kredkowa 22, 22-666 Wałbrzych</adres>
      </firma-transportowa>
      <data>2009-02-12</data>
      <data-przydatnosci>2009-02-13</data-przydatnosci>
      <jakosc>1</jakosc>
      <cena waluta="PLN">5</cena>
      <opis-uszkodzen>Lekko nieświeże</opis-uszkodzen>
    </dostawa>
  </dostawy>
</transakcje>
